version: '3.6'

services:
  # Контейнер с Node.js
  app:
    container_name: app_ReactJS
    build:
      context: ./ReactJS_app
      target: prod
    working_dir: /opt/app
    volumes:
      - volume_static:/opt/app/build
    env_file:
      - .env
    expose:
      - '3000'
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000" ]
      interval: 5s
      timeout: 2s
      retries: 15
    command: [ "npm", "run", "start" ]

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v3
    tty: true
    environment:
      CENTRIFUGO_HEALTH: "true"
    ports:
      - "8086:8086"
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    healthcheck:
      test: [ "CMD", "sh", "-c", "wget -nv -O - http://localhost:8086/health" ]
      interval: 3s
      timeout: 3s
      retries: 3
    depends_on:
      - app
    command: centrifugo -c config.json --port 8086

  keycloak:
    container_name: keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_ADDR: ${POSTGRESQL_HOST}
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_LOGLEVEL: "INFO"
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
      interval: 5s
      timeout: 2s
      retries: 15
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    depends_on:
      - postgres
    restart: unless-stopped
    command: [ "-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled" ]

  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    volumes:
      - /postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:alpine
    restart: unless-stopped
    volumes:
      - /portainer:/data_portainer/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9000 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s


  # Контейнер с nginx
  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - postgres
    image: nginx:${NGINX_VERSION}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data/certbot/conf:/etc/letsencrypt:ro
      - ./nginx/data/certbot/www:/var/www/certbot:ro
      - volume_static:/var/www/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 2s
      retries: 15
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    # Перезапустит nginx контейнер каждые 6 часов и подгрузит новые сертификаты, если есть

  certbot:
    # Новый контейнер, который запуститься вместе с nginx
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    restart: unless-stopped
    depends_on:
      - nginx
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # Проверяет каждые 12 часов, нужны ли новые сертификаты
volumes:
  volume_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /ReactJS_app/build